### PR TITLE
Added Kyrgyz translation

### PR DESCRIPTION
**Pull request by imanalopher**

### CODE REVIEW

**Comment by weaverryan** [comment]
@akovalyov there are some pending PR's for translations and translation fixes - would you have time to merge them and tag?

**Comment by weaverryan** [comment]
Hi @imanalopher!

Symfony follows the [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) standard. Kyrgyz's code is listed as `ky` there. I *believe* this file should use `ky` - but I also don't see any Kyrgyz translation files in Symfony's core or FOSUserBundle. So, I'm not 100% sure what to do :).

Thanks!

**Comment by imanalopher** [comment]
Hi @weaverryan i have pushed as you want `ky` and know in FOSUserBundle have `ky` Kyrgyz translation

**Comment by weaverryan** [comment]
You're the best @imanalopher - thank you!

**Comment by imanalopher** [comment]
@weaverryan Thank you!

**Pull request merged**
