### PR TITLE
 Updated duration translation for NB

### PR DESCRIPTION
**Pull request by ahaaje**
This adds the #181 duration translation for "Norsk bokmål" NB locale

### CODE REVIEW

**Review by kbond — CHANGES_REQUESTED** [review]
Thanks for working on this @ahaaje

**Comment by weaverryan** [comment]
Thanks @ahaaje!

**Comment by kbond** [comment]
@ahaaje, is it expected that `duration.day` and `duration.none` are missing?

**Comment by weaverryan** [comment]
Oh yea, I just noticed that also!

**Comment by kbond** [comment]
I think it's because the snippet in #181 has an unfortunate scroll :)

**Comment by ahaaje** [comment]
Yes, I did not see them there. I will update

**Pull request merged**
