### PR TITLE
Fix symfony 4.2 transChoice deprecation

### PR DESCRIPTION
**Pull request by dirkkredler**

### CODE REVIEW

**Comment by NiR-** [comment]
Thank you for this PR :)

**Comment by arteniioleg** [comment]
Create new release please. [It's not included in 1.8.0](https://github.com/KnpLabs/KnpTimeBundle/compare/1.8.0...8111778efe2b5c5065ffc5e81b56c5580e49f690).
I fixed all deprecation warnings in my project except this.

**Comment by oleg-mtr** [comment]
Up

**Comment by NiR-** [comment]
@arteniioleg I just released a new version ;)

**Comment by jimiero** [comment]
@NiR- unfortunately, this broke compatibility on symfony 2.8.x now you get: 

"1 day ago|3 days ago"

**Comment by jimiero** [comment]
If I change back this, it works as it should :(

**Comment by NiR-** [comment]
Looks like I merged this PR too fast :( I'll look into this issue, probably tomorrow ;)

**Comment by edwines** [comment]
Same issue than @jimiero but in symfony 4.1

**Comment by jacquesndl** [comment]
Same issue for me with sf 4.1 too

**Comment by colinodell** [comment]
I can also confirm @jimiero's issue on Symfony 2.8.

**Comment by ampaze** [comment]
Shouldn't it be possible to mark Version 1.9.0 to require Symfony 4.2.x via composer.json?

**Comment by Rikijs** [comment]
I am having same problem as @jimiero, but on Symfony v3.4.22.

**Comment by fyrye** [comment]
Shouldn't this change also have failed the `2.*-3.*` unit testing?

**Pull request merged**
