### PR TITLE
Adding serbian latin translation

### PR DESCRIPTION
**Pull request by cvele**

### CODE REVIEW

**Comment by akovalyov** [comment]
@umpirsky does it seem valid for you?

**Comment by umpirsky** [comment]
@cvele Good job, thanks. @akovalyov Good to go! :+1:

**Comment by cvele** [comment]
Actually this seems to have a bug, at least on my deployment. 
For some reason translations with just two variants fail to load and are producing exceptions.

    <target>{1}pre 1 minut|{2, Inf}pre %count% minuta</target>

Not really sure why tho. Probably best to rollback this until it is resolved.

**Comment by umpirsky** [comment]
@cvele Reverted, thanks for the heads up. :+1:

**Pull request merged**
