### PR TITLE
use namespaced twig classes

### LINKED ISSUE #122: Allow Symfony 5
Symfony5 is out, not sure what's needed to update this bundle.  My attempt to simply bump the dependencies didn't work, can we drop PHP5 support?

Also, I think symfony/templating has been deprecated in favor of twig/twig, but I'm not sure how to provide BC for this.

### LINKED ISSUE #125: Bug on latest version of twig bundle
On latest version of twig bundle an error occurred:

> Attempted to load class "Twig_Extension" from the global namespace.  
> !!    Did you forget a "use" statement? 

Using the "Twig_Extension" class is deprecated since Twig version 2.7

You can check it if install Symfony 5 and then try to install KnpTimeBundle

### PR DESCRIPTION
**Pull request by zaggi-iwnl**
made a mistake in the previous pr, this should be okay now.

this fixes #125, fixes #122 and makes the bundle work for twig 3.x.

see https://symfony.com/blog/preparing-your-applications-for-twig-3

### CODE REVIEW

**Comment by emovere** [comment]
Please merge this pr @weaverryan to make it compatible with twig 3 & sf 5. Thank you!

**Comment by emovere** [comment]
There seems to be a problem with this commit?

I added this into my composer.json:
`
    "require": {
        "knplabs/knp-time-bundle": "dev-master",
},
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/zaggi-iwnl/KnpTimeBundle"
        }
    ],
`

Installation:
`
% composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Restricting packages listed in "symfony/symfony" to "5.0.*"
Package operations: 2 installs, 0 updates, 0 removals
  - Installing symfony/templating (v5.0.2): Loading from cache
  - Installing knplabs/knp-time-bundle (dev-master 714b0ec): Downloading (100%) Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 1 recipe (b25a807eab05b2a0b28d8ec443bd71ab)
  - Configuring knplabs/knp-time-bundle (>=dev-master): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!   // Clearing the cache for the dev environment with debug                       
!!   // true                                                                        
!!  
!!  14:30:05 CRITICAL  [php] Uncaught Error: Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct() must be an instance of Symfony\Component\Translation\TranslatorInterface, instance of Symfony\Component\Translation\DataCollectorTranslator given, called in /Users/USERNAME/Sites/apps/PROJECT/var/cache/dev/ContainerSKffxCI/App_KernelDevDebugContainer.php on line 1775 ["exception" => TypeError { …}]
!!  
!!  In DateTimeFormatter.php line 17:
!!                                                                                 
!!    Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct()  
!!     must be an instance of Symfony\Component\Translation\TranslatorInterface,   
!!    instance of Symfony\Component\Translation\DataCollectorTranslator given, ca  
!!    lled in /Users/USERNAME/Sites/apps/PROJECT/var/cache/dev/  
!!    ContainerSKffxCI/App_KernelDevDebugContainer.php on line 1775                
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!  
!!  
Script @auto-scripts was called via post-update-cmd
`

I have the latest Twig3 & SF5.0.2 installed.

**Comment by emovere** [comment]
I have found a working Solution, changes on DateTimeFormatter.php:

Line 5 old:
`    use Symfony\Component\Translation\TranslatorInterface;`

Line 5 new:
`    use Symfony\Component\Translation\DataCollectorTranslator;`

Line 17 old:
`    public function __construct(TranslatorInterface $translator)`

Line 17 new:
`    public function __construct(DataCollectorTranslator $translator)`

**Comment by weaverryan** [comment]
Thank you @zaggi-iwnl!

**Pull request merged**
